apiVersion: v1
kind: ConfigMap
metadata:
  name: bekiratech-secret
  labels:
    app: bekiratech
data:
  DATASOURCE_USER: user
  DATASOURCE_PASSWORD: ciao123
  DATASOURCE_URL: postgresql://postgres-service:5432/kiratech