apiVersion: apps/v1
kind: Deployment
metadata:
  name: fekiratech
spec:
  selector:
    matchLabels:
      app: fekiratech
  template:
    metadata:
      labels:
        app: fekiratech
    spec:
      containers:
      - name: fekiratech
        image: erdidocky/fekiratech:latest
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 4200

---

apiVersion: v1
kind: Service
metadata:
  name: fekiratech-service
  labels:
    app: fekiratech
spec:
  type: NodePort 
  selector:
    app: fekiratech
  ports:
  - protocol: TCP
    port: 4200  
    targetPort: 4200  
    nodePort: 30001  